config/routes.rb
Pinterest::Application.routes.draw do
  
  get "users/show"
  resources :pins
  devise_for :users
  resources :users, :only => :show

  
  root 'pins#index'

  get 'home' => 'pages#index'
  get 'aboutus' => 'pages#aboutus'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	mount_uploader :photo, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :phone) }
  end

end

 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def aboutus
	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :photo)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	#@pins = Pin.where(:user_id => @user.id)
  	@pins = @user.pins
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterest</title>
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap-theme.min.css">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	 <!-- Latest compiled and minified CSS -->

<!-- Latest compiled and minified JavaScript -->
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation" style="margin-bottom: 0px">
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <a class="navbar-brand"  style="color: black" href="<%= root_path %>">Pinterest</a>
	  </div>

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    <ul class="nav navbar-nav">
	      <li class="active"><a href="#">Link</a></li>
	      <li><a href="#">Link</a></li>
	      
	    </ul>
	    <ul class="nav navbar-nav navbar-right">
	    	<li>
		      <% if current_user.nil? %>
		      	<a href="<%= new_user_session_path%>">ingreso usuarios</a>
	      <% else %>
	      	<li><a>Hola <%= current_user.email %></a></li>
	      	<li><a data-method="delete" href="/users/sign_out" rel="nofollow">salir</a>
	      	</li>

	      <% end %>

	      </li>
	      

	    </ul>
	   

	  </div><!-- /.navbar-collapse -->
	</nav>
<div class="notice"><%= notice %></div>
<div class="alert"><%= alert %></div>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
	<div class="jumbotron">
	  <h1>Hello, world!</h1>
	  <p>pinterest sube tus fotos</p>
	  <p> <%= link_to( "Conoce más", pins_path, :class => "btn btn-success btn-lg") %> </p>

	</div>
<div class="container">
	<div class="row">
			  <div class="col-md-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</div>
			<div class="col-md-8"> 
			   <img src="/assets/barco.jpg" class="img-circle">
			</div>
	</div>
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">
	<div class="well">
		<h1>Editing pin</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @pin %> |
		<%= link_to 'Back', pins_path %>
		</div>
</div>

app/views/pins/index.html.erb
<div class="container">

<%= link_to 'New Pin', new_pin_path, :class => 'btn btn-primary', :style => 'color:white' %>

  <h1>Listing pins</h1>


  <% @pins.each do |pin| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to(image_tag(pin.photo, :class => 'img-responsive'),pin) %>
        <%= pin.description %>
        <br>
        <%= link_to 'Editar', edit_pin_path(pin), :class => 'btn btn-primary', :style => 'color:white' %>
        <%= link_to 'Borrar', pin, method: :delete, data: { confirm: 'Estás seguro?' }, :class => 'btn btn-danger', :style => 'color:white'  %>
      </div>
    </div>
   <% end %>

  </div>

app/views/pins/new.html.erb
<div class="container">
	<div class="well">
		<h1>New pin</h1>

		<%= render 'form' %>

		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/show.html.erb
<div class="container">
	<div class="well">	

		

		<p>
		  <strong>Description:</strong>
		  <%= @pin.description %>
		</p>

		<p>
		  <strong>Photo:</strong>
		  <%=  image_tag(@pin.photo, :class => 'img-responsive') %>
		</p>

		<%= link_to 'Edit', edit_pin_path(@pin) %> |
		<%= link_to 'Back', pins_path %>

	</div>
</div>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/users/show.html.erb
<div class="container">

<%= link_to 'New Pin', new_pin_path, :class => 'btn btn-primary', :style => 'color:white' %>

  <h1>Listing pins</h1>


  <% @pins.each do |pin| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to(image_tag(pin.photo, :class => 'img-responsive'),pin) %>
        <%= pin.description %>
        <br>
        <%= link_to 'Editar', edit_pin_path(pin), :class => 'btn btn-primary', :style => 'color:white' %>
        <%= link_to 'Borrar', pin, method: :delete, data: { confirm: 'Estás seguro?' }, :class => 'btn btn-danger', :style => 'color:white'  %>
      </div>
    </div>
   <% end %>

  </div>